### ISSUE TITLE
Add calculations for RATIONALCALC

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/orient#18]
https://github.com/filecoin-project/research/issues/123 (cc: @mhammersley)

**Comment by porcuquine** [comment]
@nikkolasg @irenegiacomelli Can one of you point me to a canonical public source for these calculations and related parameters — or else add notes in comments here?

**Comment by irenegiacomelli** [comment]
@porcuquine The only pointer I have is the one to the[ google doc](https://docs.google.com/document/d/19tXXmn8lV4zh1wKeGIiiZQ_B4BkSHmdnzzoNYwvzYTk/edit#heading=h.wwle5veib6b8) used to take nodes during the research week in London.

**Comment by porcuquine** [comment]
Ubercalc now belongs in Filecoin spec.
