### ISSUE TITLE
Add EC parameter calculations

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/orient#19]
Paused until @sternhenri is available to coordinate.

**Comment by sternhenri** [comment]
Full EC parametrization work is here: 
https://github.com/filecoin-project/consensus/issues/75

Moving this from a manual-crank algorithm to an automated/integrated one is super exciting. I am now ready and available. At your disposal

**Comment by porcuquine** [comment]
Ubercalc now belongs in Filecoin spec.
